openapi: 3.1.0
info:
  title: Glasses8P API
  description: API for user signup, login, and contact management
  version: 1.0.0
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/DROBINSON4105_1/Glasses8P/1.0.0
  - url: http://glasses8p.online/api/
paths:
  /signup:
    post:
      summary: Register a new user
      operationId: signUp
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The ID of the created user
                  error:
                    type: string
                    description: Error message (blank if no error)
        '400':
          description: Invalid input
        '409':
          description: Account with provided username already exists